# Generated by Django 2.2 on 2022-02-08 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='محتوا')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='تصاویر')),
                ('create', models.DateTimeField(verbose_name='زمان ساخت')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('update', models.DateTimeField(verbose_name='بروز رسانی در')),
                ('status', models.CharField(choices=[('publish', 'منتشر شد'), ('draft', 'پیش نویس'), ('lock', 'در انتظار تعیین وظعیت'), ('back', 'رد شد!!')], max_length=30, verbose_name='وظعیت')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندیها',
                'ordering': ['publish'],
            },
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='آدرس'),
        ),
    ]
