# Generated by Django 2.2 on 2022-02-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('blog', '0002_auto_20220208_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['publish'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='account.User', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ManyToManyField(related_name='children', to='blog.CategoryModel', verbose_name='دسته بندی'),
        ),
    ]
